# setup
setup: classification

# Loss
criterion: classification
criterion_kwargs:
   entropy_weight: 2
   inconsistency_weight: 0.05

# Weight update
update_cluster_head_only: False # Update full network in classification
num_heads: 2 # Only use one head

# Model
backbone: resnet_ts
res_kwargs:
  in_channels: 2
  mid_channels: 12
  use_lstm: false

# Dataset
train_db_name: sre
val_db_name: sre
num_classes: 10
num_neighbors: 5

# Transformations
augmentation_strategy: ts
transformation_kwargs:
   noise_sigma: 0.01

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.01
   weight_decay: 0.001
epochs: 50
batch_size: 512
num_workers: 0

# Scheduler
scheduler: constant

anomaly_kwargs:
   portion: 0.99